# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "chatbot-app2.0"
client_id = "372ef44d9a7d7a45348cc11af6b5e893"
application_url = "https://pottery-cubic-maiden-copyright.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://pottery-cubic-maiden-copyright.trycloudflare.com/auth/callback",
  "https://pottery-cubic-maiden-copyright.trycloudflare.com/auth/shopify/callback",
  "https://pottery-cubic-maiden-copyright.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-e99ae767.myshopify.com"
